name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-ios:
    name: "macOS 12 (Xcode 14.0)"
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.0
        run: sudo xcode-select -s /Applications/Xcode_14.0.app
      - name: Run tests
        run: make test-ios
