name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-ios:
    name: "macOS 13 (Xcode 15.0)"
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app
      - name: Run tests
        run: make test-ios
